### ISSUE TITLE
Sling File Upload Failed

### ISSUE THREAD

**Issue by pakman198** [mnlsn/gulp-slang#5]
Hi im working on a project with AEM and SASS. after compiling the styles, sling tries to upload a file, but it fails, it says:
File Upload Failed - Check username and password

i follwed this tutorial:
[http://aesinv.com/development/2016/05/04/simplified-aem-frontend-sass.html](url)
and generated a gulp file similar to what is shown there.

Any help is appreciated, thanks in advance

**Comment by stomx** [comment]
If your password contains special characters, it may be because of encoding problems.
Please check that the issue has been resolved two days ago.

Translated into Google Translator.

---

비밀번호에 특수문자가 있었다면 인코딩문제로 문제가 발생했을 수 있습니다.
2일 전에 해당 이슈 해결되었으니 확인해보세요.

**Comment by pakman198** [comment]
Thanks for your reply

I ended up using another solution, but it seems the problem in all the solutions I tried was setting en environment variable on Windows for NO_PROXY=localhost
Apparently that solves the problem of node trying to do a POST request when using corporate proxy

**Comment by reenumathew** [comment]
@pakman198  : I was facing the same issue and the solution you suggested fixed it. Thanks

**Comment by pakman198** [comment]
@reenumathew glad it was helpful 😄
